### ISSUE TITLE
Wifi speed is always 0

### ISSUE THREAD

**Issue by Tomin1** [Tomin1/wifisignalstrength#4]
For some reason my laptop (Dell XPS13, model 9333) started showing speed of 0 Mb/s constantly which can not be true since the wifi works just fine. I don't know what caused this but it could have been either of two things: I did recently update my BIOS (UEFI) and I have installed new updates recently. Either of them could have caused this.

If anyone else sees this problem please comment here.

Two things I noticed: First NetworkManager doesn't show wifi speed either (not surprising) so it might be that it can't figure it out. Second there is nothing in `/sys/class/net/wlp2s0/wireless/` so I would guess that this is some driver issue caused by Linux or BIOS.

**Comment by mumblyOMOD** [comment]
I have the same behavior on 2 of my laptops, a Thinkpad X220 Tablet and a Asus Q502LA, both with an Intel 7260AC mpcie wifi card. I also see nothing in /sys/class/net/wlp2s0/wireless/.
Let me know if there's any testing that I can do to help.

**Comment by Tomin1** [comment]
This doesn't seem to be a problem on my laptop anymore. Closing.
